### ISSUE TITLE
BUG: CLI preview events returns divided by 0

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_app#46]
1. Create preview from compose file

<details><summary>File: Click to expand</summary>

```
services:
  webhook:
    image: uffizzitest/webhooks-test-app:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TEST: test1


x-uffizzi-ingress:
  service: webhook
  port: 80

x-uffizzi-continuous-preview:
  share_to_github: true
  delete_preview_after: 99h
  tag_pattern: uffizzi_request_*
  delete_preview_when_image_tag_is_updated: true
  deploy_preview_when_image_tag_is_created: true
  delete_preview_when_pull_request_is_closed: true
  deploy_preview_when_pull_request_is_opened: true

```

</details>

2. Run `uffizzi preview events DEPLOYMENT-ID`

Result: Error `divided by 0`

<details><summary>Error: Click to expand</summary>

```
~ # uffizzi preview events deployment-7
/usr/local/bundle/gems/thor-1.2.1/lib/thor/shell/basic.rb:168:in `%': divided by 0 (ZeroDivisionError)
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/shell/basic.rb:168:in `block in print_in_columns'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/shell/basic.rb:166:in `each'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/shell/basic.rb:166:in `each_with_index'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/shell/basic.rb:166:in `print_in_columns'
	from /usr/local/bundle/gems/uffizzi-cli-0.3.8/lib/uffizzi/shell.rb:21:in `print_in_columns'
	from /usr/local/bundle/gems/uffizzi-cli-0.3.8/lib/uffizzi/cli/preview.rb:116:in `handle_succeed_events_response'
	from /usr/local/bundle/gems/uffizzi-cli-0.3.8/lib/uffizzi/cli/preview.rb:109:in `handle_events_command'
	from /usr/local/bundle/gems/uffizzi-cli-0.3.8/lib/uffizzi/cli/preview.rb:76:in `run'
	from /usr/local/bundle/gems/uffizzi-cli-0.3.8/lib/uffizzi/cli/preview.rb:55:in `events'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/uffizzi-cli-0.3.8/exe/uffizzi:5:in `<top (required)>'
	from /usr/local/bundle/bin/uffizzi:25:in `load'
	from /usr/local/bundle/bin/uffizzi:25:in `<main>'
```

</details>

Events for preview was returned by API `/api/cli/v1/projects/{project_slug}/deployments/{deployment_id}/events`

<details><summary>From API: Click to expand</summary>
![image](/uploads/e6718937f60e179efcb02ffda41935a0/image.png)

```
{
    "events": [
        {
            "first_timestamp": null,
            "last_timestamp": null,
            "reason": "Scheduled",
            "message": "Successfully assigned deployment-7/app-deployment-7-6fcf7dd489-jscj5 to gke-uffizzi-client-sandbox-510ebd16-vmes"
        },
        {
            "first_timestamp": "2022-03-29T14:44:04Z",
            "last_timestamp": "2022-03-29T14:44:04Z",
            "reason": "Pulling",
            "message": "Pulling image \"uffizzitest/webhooks-test-app:latest\""
        },
        {
            "first_timestamp": "2022-03-29T14:44:05Z",
            "last_timestamp": "2022-03-29T14:44:05Z",
            "reason": "Pulled",
            "message": "Successfully pulled image \"uffizzitest/webhooks-test-app:latest\" in 455.548757ms"
        },
        {
            "first_timestamp": "2022-03-29T14:44:05Z",
            "last_timestamp": "2022-03-29T14:44:05Z",
            "reason": "Created",
            "message": "Created container a74ced40d3"
        },
        {
            "first_timestamp": "2022-03-29T14:44:06Z",
            "last_timestamp": "2022-03-29T14:44:06Z",
            "reason": "Started",
            "message": "Started container a74ced40d3"
        },
        {
            "first_timestamp": null,
            "last_timestamp": null,
            "reason": "Scheduled",
            "message": "Successfully assigned deployment-7/cm-acme-http-solver-mbkx2 to gke-uffizzi-client-default-pool-34f79102-s0ri"
        },
        {
            "first_timestamp": "2022-03-29T14:43:53Z",
            "last_timestamp": "2022-03-29T14:43:53Z",
            "reason": "Pulled",
            "message": "Container image \"quay.io/jetstack/cert-manager-acmesolver:v1.6.1\" already present on machine"
        },
        {
            "first_timestamp": "2022-03-29T14:43:54Z",
            "last_timestamp": "2022-03-29T14:43:54Z",
            "reason": "Created",
            "message": "Created container acmesolver"
        },
        {
            "first_timestamp": "2022-03-29T14:43:54Z",
            "last_timestamp": "2022-03-29T14:43:54Z",
            "reason": "Started",
            "message": "Started container acmesolver"
        },
        {
            "first_timestamp": "2022-03-29T14:44:13Z",
            "last_timestamp": "2022-03-29T14:44:13Z",
            "reason": "Killing",
            "message": "Stopping container acmesolver"
        }
    ]
}
```

</details>

**Comment by moklidia** [comment]
The output is displayed in pretty print format

**Comment by moklidia** [comment]
The issue was opened in the UffizziCli project

https://github.com/UffizziCloud/uffizzi_cli/issues/49
